### ISSUE TITLE
Transfer Cycling '74 n4m-examples to here

### ISSUE THREAD

**Issue by catarak** [Cycling74/n4m-core-examples#1]
@fde31 and @starakaj, what examples in [Cyling74/n4m-examples](https://github.com/Cycling74/n4m-examples) are core examples and should be in this repo? let's discuss!

**Comment by starakaj** [comment]
Okay, I'll start by proposing that we need three examples in this core repository.
1. Hello world. Documents the basics of getting Max to work with Node.
2. Async/await. Introduces the idea of asynchronous programming. Maybe does something with the filesystem too, demonstrating how to work with node core modules.
3. Alternate entry point. We have people trying to run Node from the command line, and of course it can't find the "max-api" module. There are basically three ways around this: using a try/catch, some kind of argument that causes a conditional require, or defining an alternate entry point (max-entry.js) that basically accomplishes the same thing. We should decide between 2 and 3, and then make the example. Otherwise people are gonna do 1, since it's easiest.

**Comment by fde31** [comment]
I like the list proposed by @starakaj! Unfortunately it might be hard to do 1 without 2 but maybe 2 can just be an extended draft of async/await usage?! One thing for that might be to explain why and how. For example one user already ran into an issue with a stalling Node process when loading and processing a 50mb (that's what I recall) file from disk using the sync calls.

For 3. Both are very valid. "try/catch" seems easiest for small size projects, while I do think 2 is the even cleaner way to go but maybe overkill unless writing a bigger application?! 

Were u thinking of going through all API endpoints for 1 @starakaj ?

There was also a request for using user/system domain Node installs once we fully support that with node.script I'd like to make sure we include this in here even if it might be considered "advanced"?!

**Comment by catarak** [comment]
i guess 1. would include
- maxApi.post
- maxApi.addHandler, with no arguments, some specified number of arguments, unspecified number of arguments
- maxApi.outlet, with different numbers of arguments

**Comment by pixlpa** [comment]
I'll just chime in here with my 3 cents. 
1. Just do a simple I/O Max.addhandler, Max.post,Max.outlet as Cassie says
2. This should be in context, since there are lots of places you can learn async/await, but we should find a reason to use it in a Max setting. Doing file read/write or an API request seem like good places to stick it.
3. I've used the try/catch one in my camera project, because it's the easiest as you say. I don't know what the right solution is there, but I think it's smart for us to make a recommendation. It's likely going to be a popular workflow to move between Max and Terminal dev, especially with node debugging tools.

As a side note, I think it's useful to also think about the Max patch side of any examples we do, in terms of what we want to encourage as patterns for patching along with node.script. For example, putting a route object in to handle the outlet calls, and how to work with npm messages. Speaking of, I think it's good to talk a little about how NPM fits into the Node for Max workflow. I usually start from Terminal so I've already done npm init, etc, but I wonder if we want to embrace that workflow or not.

**Comment by catarak** [comment]
@pixlpa agree about patching patterns! as part of (1) i tried to show how to use route. 

in working with npm messages, what do you think is not included in the current node.script help files?
